ALTER TABLE DOCENTI DROP PRIMARY KEY;
ALTER TABLE P02_RISPOSTE  DROP PRIMARY KEY;
ALTER TABLE P06_CDS  DROP PRIMARY KEY;
ALTER TABLE P07_NORMATIVA  DROP PRIMARY KEY;
ALTER TABLE P09_AD_GEN DROP PRIMARY KEY;
ALTER TABLE ELEMENTI   DROP PRIMARY KEY;
ALTER TABLE P01_SCUOLA DROP PRIMARY KEY;
ALTER TABLE P02_QUESITI  DROP PRIMARY KEY;
ALTER TABLE P02_QUEST_COMP  DROP PRIMARY KEY;
ALTER TABLE P02_RISPOSTE DROP PRIMARY KEY;
ALTER TABLE P02_TIPI_FORMATO DROP PRIMARY KEY;
ALTER TABLE P06_CDS  DROP PRIMARY KEY;
ALTER TABLE P06_FAC  DROP PRIMARY KEY;
ALTER TABLE P06_FAC_CDS DROP PRIMARY KEY;
ALTER TABLE P07_NORMATIVA  DROP PRIMARY KEY;
ALTER TABLE P09_AD_GEN DROP PRIMARY KEY;
ALTER TABLE P09_UD_CDS DROP PRIMARY KEY;
ALTER TABLE P09_UD_PDSORD_DOC  DROP PRIMARY KEY;
ALTER TABLE TIPI_CORSO  DROP PRIMARY KEY;
ALTER TABLE TIPI_TITOLO_SUP  DROP PRIMARY KEY;


DROP INDEX IDX1_Q35_INVIO_SEGNALAZIONE ON Q35_INVIO_SEGNALAZIONE;

DROP INDEX IDX1_Q35_DATI_COMP ON Q35_DATI_COMP;
DROP INDEX IDX2_Q35_DATI_COMP ON Q35_DATI_COMP; 
DROP INDEX IDX3_Q35_DATI_COMP ON Q35_DATI_COMP; 
DROP INDEX IDX4_Q35_DATI_COMP ON Q35_DATI_COMP; 
DROP INDEX IDX5_Q35_DATI_COMP ON Q35_DATI_COMP; 
DROP INDEX IDX6_Q35_DATI_COMP ON Q35_DATI_COMP; 
DROP INDEX IDX7_Q35_DATI_COMP ON Q35_DATI_COMP; 
DROP INDEX IDX8_Q35_DATI_COMP ON Q35_DATI_COMP; 
DROP INDEX IDX9_Q35_DATI_COMP ON Q35_DATI_COMP; 
DROP INDEX IDX10_Q35_DATI_COMP ON Q35_DATI_COMP; 
DROP INDEX IDX11_Q35_DATI_COMP ON Q35_DATI_COMP; 
DROP INDEX IDX12_Q35_DATI_COMP ON Q35_DATI_COMP; 
DROP INDEX IDX13_Q35_DATI_COMP ON Q35_DATI_COMP; 
DROP INDEX IDX14_Q35_DATI_COMP ON Q35_DATI_COMP; 

DROP INDEX XIF_TIPITITOLOSUP_MRTPDPLM_01 ON TIPI_TITOLO_SUP; 
DROP INDEX XIF_TIPITITOLOSUP_TPSTSP_01 ON TIPI_TITOLO_SUP;  

DROP INDEX IDX1_V06_CARICHE_SDR_VALIDE ON V06_CARICHE_SDR_VALIDE; 

DROP INDEX IDX1_P06_DIP ON P06_DIP; 

DROP INDEX XIF_DOCENTI_P01CM_01 ON DOCENTI; 
DROP INDEX XIF_DOCENTI_P01FRM_01 ON DOCENTI;  
DROP INDEX XIF_DOCENTI_P01LCLT_01 ON DOCENTI; 
DROP INDEX XIF_DOCENTI_P01NZ_01 ON DOCENTI; 
DROP INDEX XIF_DOCENTI_P01PRCLLLR_01 ON DOCENTI; 
DROP INDEX XIF_DOCENTI_P06DP_01 ON DOCENTI; 
DROP INDEX XIF_DOCENTI_P06FC_01 ON DOCENTI; 
DROP INDEX XIF_DOCENTI_P06TN_01 ON DOCENTI; 
DROP INDEX XIF_DOCENTI_P07STT_01 ON DOCENTI; 
DROP INDEX XIF_DOCENTI_RGDT_01 ON DOCENTI; 
DROP INDEX XIF_DOCENTI_RLDC_01 ON DOCENTI; 

DROP INDEX XIF_ELEMENTI_P06CNTST_01 ON ELEMENTI; 
DROP INDEX XIF_ELEMENTI_TPLM_01 ON ELEMENTI; 
DROP INDEX XIF_ELEMENTI_TPVNCSSST_01 ON ELEMENTI; 
DROP INDEX XIF_ELEMENTI_TPVNCSSST_02 ON ELEMENTI; 
  
DROP INDEX XIF_P01SCUOLA_MRSCL_01 ON P01_SCUOLA; 
DROP INDEX XIF_P01SCUOLA_P01CM_01 ON P01_SCUOLA; 
DROP INDEX XIF_P01SCUOLA_TPSTSP_01 ON P01_SCUOLA; 
DROP INDEX XIF_P01SCUOLA_TPST_01 ON P01_SCUOLA; 
  
DROP INDEX XIF_P02QSTP05FRMLCLCTSS_01 ON P02_QUESITI; 
DROP INDEX XIF_P02QUESITI_LMNT_01 ON P02_QUESITI; 
DROP INDEX XIF_P02QUESITI_P02CTGR_01 ON P02_QUESITI; 
DROP INDEX XIF_P02QUESITI_P02PRCTTQST_01 ON P02_QUESITI; 
DROP INDEX XIF_P02QUESITI_P02QST_01 ON P02_QUESITI; 
DROP INDEX XIF_P02QUESITI_P02TGS_01 ON P02_QUESITI; 
DROP INDEX XIF_P02QUESITI_P02TPFRMT_01 ON P02_QUESITI; 
DROP INDEX XIF_P02QUESITI_P02TPLYT_01 ON P02_QUESITI; 
DROP INDEX XIF_P02QUESITI_P05CNDVRMPRT_01 ON P02_QUESITI; 
DROP INDEX XIF_P02QUESITI_P08NSGRP_01 ON P02_QUESITI; 
DROP INDEX XIF_P02QUESITI_P08PTSCGRP_01 ON P02_QUESITI; 
DROP INDEX XIF_P02_QUESITI_OPDOM ON P02_QUESITI; 
  
DROP INDEX XIF_P02QUESTCOMP_P02QSTNR_01 ON P02_QUEST_COMP; 
DROP INDEX XIF_P02QUESTCOMP_P02STTQST_01 ON P02_QUEST_COMP; 
DROP INDEX XIF_P02QUESTCOMP_VNTCMPQST_01 ON P02_QUEST_COMP; 
  
DROP INDEX XIF_P02RISPOSTE_P02QSTCMP_01 ON P02_RISPOSTE; 
	
DROP INDEX XIF_P02TIPIFORMATO_TPLM_01 ON P02_TIPI_FORMATO; 
	 
DROP INDEX IDX$$_CD290008 ON P06_CDS; 
DROP INDEX XIE_P06CDS_P07CLAAREE ON P06_CDS; 
DROP INDEX XIF_P06CDS_DRECRETI_01 ON P06_CDS; 
DROP INDEX XIF_P06CDS_MPS_01 ON P06_CDS;
DROP INDEX XIF_P06CDS_P06CDSRNGMT_01 ON P06_CDS; 
DROP INDEX XIF_P06CDS_P06NTST_01 ON P06_CDS; 
DROP INDEX XIF_P06CDS_P06_01 ON P06_CDS; 
DROP INDEX XIF_P06CDS_P06_02 ON P06_CDS; 
DROP INDEX XIF_P06CDS_P07NRMTV_01 ON P06_CDS; 
DROP INDEX XIF_P06CDS_P13RSPCRT_01 ON P06_CDS; 
DROP INDEX XIF_P06CDS_SCLSPC_01 ON P06_CDS; 
DROP INDEX XIF_P06CDS_TPCRS_01 ON P06_CDS; 
DROP INDEX XIF_P06CDS_TPDD_01 ON P06_CDS; 
DROP INDEX XIF_P06CDS_TPMSTR_01 ON P06_CDS;
DROP INDEX XIF_P06CDS_TPSCLSPC_01 ON P06_CDS;
DROP INDEX XIF_P06CDS_TPSTT_01 ON P06_CDS;
DROP INDEX XIF_P06CDS_TPTTT_01 ON P06_CDS; 

DROP INDEX IDX$$_CD29000C ON P06_FAC_CDS; 
DROP INDEX XIF_P06FACCDS_P06CDS_01 ON P06_FAC_CDS; 
DROP INDEX XIF_P06FACCDS_P06FC_01 ON P06_FAC_CDS; 
  
DROP INDEX XIF_P09UDCDS_P09DCDS_01 ON P09_UD_CDS; 
DROP INDEX XIF_P09UDCDS_TPD_01 ON P09_UD_CDS; 
  
DROP INDEX XIEP09UDPDSORDDOC_ADDOC ON P09_UD_PDSORD_DOC; 
DROP INDEX XIF_P09DPDSRDDCP09DPDSRD_01 ON P09_UD_PDSORD_DOC; 
DROP INDEX XIF_P09UDPDSORDDOC_DCNT_01 ON P09_UD_PDSORD_DOC; 
DROP INDEX XIF_P09UDPDSORDDOC_TPCPRTR_01 ON P09_UD_PDSORD_DOC; 
  
DROP INDEX IDX$$_243430003 ON TIPI_CORSO; 
DROP INDEX XIF_TIPICORSO_MRTPLR_01 ON TIPI_CORSO; 
DROP INDEX XIF_TIPICORSO_P07NRMTV_01 ON TIPI_CORSO;
DROP INDEX XIF_TIPICORSO_TPTTT_01 ON TIPI_CORSO; 
  
DROP INDEX IDX1_V02_RISPOSTE_ROW_TESTO_LIBERO ON V02_RISPOSTE_ROW_TESTO_LIBERO; 

DROP INDEX XIF_P06FAC_MIURSTRUTTURE_01 ON P06_FAC; 
DROP INDEX XIF_P06FAC_MRFCLT_01 ON P06_FAC; 
DROP INDEX XIF_P06FAC_P01CM_01 ON P06_FAC; 
DROP INDEX XIF_P06FAC_P06RDSC_01 ON P06_FAC; 
DROP INDEX XIF_P06FAC_P06TN_01 ON P06_FAC; 
DROP INDEX XIF_P06FAC_TPSDR_01 ON P06_FAC; 
DROP INDEX XIF_P06FAC_TPSTT_01 ON P06_FAC; 
  
DROP INDEX IDX1_Q35_NUM_QUEST_CDS_DOC_UD ON Q35_NUM_QUEST_CDS_DOC_UD; 


*****************************************************************************************************

CREATE INDEX IDX1_Q35_INVIO_SEGNALAZIONE ON Q35_INVIO_SEGNALAZIONE (QUEST_COMP_ID); 

CREATE INDEX IDX1_Q35_DATI_COMP ON Q35_DATI_COMP (QUEST_COMP_ID);
CREATE INDEX IDX2_Q35_DATI_COMP ON Q35_DATI_COMP (CDS_AD_ID_VAL);
CREATE INDEX IDX3_Q35_DATI_COMP ON Q35_DATI_COMP (DOC_AD_ID_VAL);
CREATE INDEX IDX4_Q35_DATI_COMP ON Q35_DATI_COMP (DOC_TIT_AD_ID_VAL);
CREATE INDEX IDX5_Q35_DATI_COMP ON Q35_DATI_COMP (FAC_ID_COMP);
CREATE INDEX IDX6_Q35_DATI_COMP ON Q35_DATI_COMP (CDS_ID_COMP);
CREATE INDEX IDX7_Q35_DATI_COMP ON Q35_DATI_COMP (AD_ID_VAL);
CREATE INDEX IDX8_Q35_DATI_COMP ON Q35_DATI_COMP (AA_OFF_AD_ID_VAL,AD_ID_VAL,CDS_AD_ID_VAL,UD_ID_VAL);
CREATE INDEX IDX9_Q35_DATI_COMP ON Q35_DATI_COMP (TIPO_TITOLO_COD_COMP);
CREATE INDEX IDX10_Q35_DATI_COMP ON Q35_DATI_COMP (SCUOLA_SUP_ID_COMP);
CREATE INDEX IDX11_Q35_DATI_COMP ON Q35_DATI_COMP (AA_OFF_AD_ID_VAL,AD_ID_VAL,CDS_AD_ID_VAL,DOC_AD_ID_VAL,UD_ID_VAL,EVENTO_COMP,STU_FREQ_FLG_COMP,STU_NO_AUT_FLG_COMP);
CREATE INDEX IDX12_Q35_DATI_COMP ON Q35_DATI_COMP (AA_OFF_AD_ID_VAL);
CREATE INDEX IDX13_Q35_DATI_COMP ON Q35_DATI_COMP (DATAORA_COMP);
CREATE INDEX IDX14_Q35_DATI_COMP ON Q35_DATI_COMP (AA_ORD_AD_ID_VAL,AD_ID_VAL,CDS_AD_ID_VAL,DOC_AD_ID_VAL,PDS_AD_ID_VAL,UD_ID_VAL);

CREATE INDEX XIF_TIPITITOLOSUP_MRTPDPLM_01 ON TIPI_TITOLO_SUP (ID_DIPLOMA);
CREATE INDEX XIF_TIPITITOLOSUP_TPSTSP_01 ON TIPI_TITOLO_SUP (TIPOLOGIA_COD);

CREATE INDEX IDX1_V06_CARICHE_SDR_VALIDE ON V06_CARICHE_SDR_VALIDE (STRUTT_ID);

CREATE INDEX IDX1_P06_DIP ON P06_DIP (DIP_ID);

CREATE INDEX XIF_DOCENTI_P01CM_01 ON DOCENTI (COM_NASC_ID);
CREATE INDEX XIF_DOCENTI_P01FRM_01 ON DOCENTI (FIRMA_ID); 
CREATE INDEX XIF_DOCENTI_P01LCLT_01 ON DOCENTI (LOCALITA_NASC_ID);
CREATE INDEX XIF_DOCENTI_P01NZ_01 ON DOCENTI (NAZI_NASC_ID);
CREATE INDEX XIF_DOCENTI_P01PRCLLLR_01 ON DOCENTI (OPER_CELLULARE);
CREATE INDEX XIF_DOCENTI_P06DP_01 ON DOCENTI (DIP_ID);
CREATE INDEX XIF_DOCENTI_P06FC_01 ON DOCENTI (FAC_ID);
CREATE INDEX XIF_DOCENTI_P06TN_01 ON DOCENTI (ATENEO_ID);
CREATE INDEX XIF_DOCENTI_P07STT_01 ON DOCENTI (SETT_COD);
CREATE INDEX XIF_DOCENTI_RGDT_01 ON DOCENTI (ORIG_DATO_COD);
CREATE INDEX XIF_DOCENTI_RLDC_01 ON DOCENTI (RUOLO_DOC_COD);

CREATE INDEX XIF_ELEMENTI_P06CNTST_01 ON ELEMENTI (CONT_COD);
CREATE INDEX XIF_ELEMENTI_TPLM_01 ON ELEMENTI (TIPO_ELEM_COD);
CREATE INDEX XIF_ELEMENTI_TPVNCSSST_01 ON ELEMENTI (TIPO_VINC_ASSIST_DETT_ID);
CREATE INDEX XIF_ELEMENTI_TPVNCSSST_02 ON ELEMENTI (TIPO_VINC_ASSIST_ID);
  
CREATE INDEX XIF_P01SCUOLA_MRSCL_01 ON P01_SCUOLA (ID_SCUOLA_MIUR);
CREATE INDEX XIF_P01SCUOLA_P01CM_01 ON P01_SCUOLA (COMUNE_ID);
CREATE INDEX XIF_P01SCUOLA_TPSTSP_01 ON P01_SCUOLA (TIPOLOGIA_COD);
CREATE INDEX XIF_P01SCUOLA_TPST_01 ON P01_SCUOLA (TIPI_IST_ID);
  
CREATE INDEX XIF_P02QSTP05FRMLCLCTSS_01 ON P02_QUESITI (FORMULA_RISP_ID) ;
CREATE INDEX XIF_P02QUESITI_LMNT_01 ON P02_QUESITI (ELEM_COD);
CREATE INDEX XIF_P02QUESITI_P02CTGR_01 ON P02_QUESITI (CATEG_COD);
CREATE INDEX XIF_P02QUESITI_P02PRCTTQST_01 ON P02_QUESITI (PROC_ATTIVA_QUEST_ID);
CREATE INDEX XIF_P02QUESITI_P02QST_01 ON P02_QUESITI (PARENT_QUESITO_ID);
CREATE INDEX XIF_P02QUESITI_P02TGS_01 ON P02_QUESITI (TAG_COD);
CREATE INDEX XIF_P02QUESITI_P02TPFRMT_01 ON P02_QUESITI (TIPO_FORMATO_COD) ;
CREATE INDEX XIF_P02QUESITI_P02TPLYT_01 ON P02_QUESITI (TIPO_LAYOUT_COD); 
CREATE INDEX XIF_P02QUESITI_P05CNDVRMPRT_01 ON P02_QUESITI (COND_ID);
CREATE INDEX XIF_P02QUESITI_P08NSGRP_01 ON P02_QUESITI (INS_ID);
CREATE INDEX XIF_P02QUESITI_P08PTSCGRP_01 ON P02_QUESITI (GRP_ESC_ID);
CREATE INDEX XIF_P02_QUESITI_OPDOM ON P02_QUESITI (OPERANDO_DOM_ID);
  
CREATE INDEX XIF_P02QUESTCOMP_P02QSTNR_01 ON P02_QUEST_COMP (QUESTIONARIO_ID);
CREATE INDEX XIF_P02QUESTCOMP_P02STTQST_01 ON P02_QUEST_COMP (STATO_QUEST_COD);
CREATE INDEX XIF_P02QUESTCOMP_VNTCMPQST_01 ON P02_QUEST_COMP (EVENTO_COMP_COD);
  
CREATE INDEX XIF_P02RISPOSTE_P02QSTCMP_01 ON P02_RISPOSTE (QUEST_COMP_ID);
	
CREATE INDEX XIF_P02TIPIFORMATO_TPLM_01 ON P02_TIPI_FORMATO (TIPO_ELEM_COD);
	 
CREATE INDEX IDX$$_CD290008 ON P06_CDS (CDS_ID, SETT_FLG) ;
CREATE INDEX XIE_P06CDS_P07CLAAREE ON P06_CDS (CLA_AREA_ID);
CREATE INDEX XIF_P06CDS_DRECRETI_01 ON P06_CDS (DECRETO_ID);
CREATE INDEX XIF_P06CDS_MPS_01 ON P06_CDS (UM_PESO_COD);
CREATE INDEX XIF_P06CDS_P06CDSRNGMT_01 ON P06_CDS (RANGE_MAT_ID);
CREATE INDEX XIF_P06CDS_P06NTST_01 ON P06_CDS (ENTE_ID);
CREATE INDEX XIF_P06CDS_P06_01 ON P06_CDS (AA_ATT_ID);
CREATE INDEX XIF_P06CDS_P06_02 ON P06_CDS (AA_DIS_ID);
CREATE INDEX XIF_P06CDS_P07NRMTV_01 ON P06_CDS (NORM_ID);
CREATE INDEX XIF_P06CDS_P13RSPCRT_01 ON P06_CDS (RESP_ID);
CREATE INDEX XIF_P06CDS_SCLSPC_01 ON P06_CDS (SCUOLA_SPEC_ID);
CREATE INDEX XIF_P06CDS_TPCRS_01 ON P06_CDS (TIPO_CORSO_COD);
CREATE INDEX XIF_P06CDS_TPDD_01 ON P06_CDS (TIPO_DID_COD);
CREATE INDEX XIF_P06CDS_TPMSTR_01 ON P06_CDS (TIPO_MASTER_COD);
CREATE INDEX XIF_P06CDS_TPSCLSPC_01 ON P06_CDS (TIPO_CORSO_COD, TIPO_SPEC_COD);
CREATE INDEX XIF_P06CDS_TPSTT_01 ON P06_CDS (ISTAT_COD);
CREATE INDEX XIF_P06CDS_TPTTT_01 ON P06_CDS (TIPO_TITIT_COD);

CREATE INDEX IDX$$_CD29000C ON P06_FAC_CDS (CDS_ID, DEF_AMM_FLG, FAC_ID);
CREATE INDEX XIF_P06FACCDS_P06CDS_01 ON P06_FAC_CDS (CDS_ID);
CREATE INDEX XIF_P06FACCDS_P06FC_01 ON P06_FAC_CDS (FAC_ID);
  
CREATE INDEX XIF_P09UDCDS_P09DCDS_01 ON P09_UD_CDS (CDS_ID, AD_ID, AA_OFF_ID);
CREATE INDEX XIF_P09UDCDS_TPD_01 ON P09_UD_CDS (TIPO_UD_COD);
  
CREATE INDEX XIEP09UDPDSORDDOC_ADDOC ON P09_UD_PDSORD_DOC (AD_ID, DOCENTE_ID);
CREATE INDEX XIF_P09DPDSRDDCP09DPDSRD_01 ON P09_UD_PDSORD_DOC (CDS_ID, AD_ID, AA_ORD_ID, PDS_ID, AA_OFF_ID, UD_ID);
CREATE INDEX XIF_P09UDPDSORDDOC_DCNT_01 ON P09_UD_PDSORD_DOC (DOCENTE_ID);
CREATE INDEX XIF_P09UDPDSORDDOC_TPCPRTR_01 ON P09_UD_PDSORD_DOC (TIPO_COPERTURA_COD);
  
CREATE INDEX IDX$$_243430003 ON TIPI_CORSO (POST_LAUREAM_FLG, TIPO_CORSO_COD);
CREATE INDEX XIF_TIPICORSO_MRTPLR_01 ON TIPI_CORSO (ID_TIPO_LAUREA);
CREATE INDEX XIF_TIPICORSO_P07NRMTV_01 ON TIPI_CORSO (NORM_ID);
CREATE INDEX XIF_TIPICORSO_TPTTT_01 ON TIPI_CORSO (TIPO_TITIT_COD);
  
CREATE INDEX IDX1_V02_RISPOSTE_ROW_TESTO_LIBERO ON V02_RISPOSTE_ROW_TESTO_LIBERO (RISPOSTA_ID);

CREATE INDEX XIF_P06FAC_MIURSTRUTTURE_01 ON P06_FAC (ID_STRUTTURA);
CREATE INDEX XIF_P06FAC_MRFCLT_01 ON P06_FAC (COD_FACOLTA);
CREATE INDEX XIF_P06FAC_P01CM_01 ON P06_FAC (COMUNE_ID); 
CREATE INDEX XIF_P06FAC_P06RDSC_01 ON P06_FAC (AREA_DISC_COD);
CREATE INDEX XIF_P06FAC_P06TN_01 ON P06_FAC (ATENEO_ID);
CREATE INDEX XIF_P06FAC_TPSDR_01 ON P06_FAC (SDR_TIP);
CREATE INDEX XIF_P06FAC_TPSTT_01 ON P06_FAC (ISTAT_COD);
  
CREATE INDEX IDX1_Q35_NUM_QUEST_CDS_DOC_UD ON Q35_NUM_QUEST_CDS_DOC_UD (AA_OFF_AD_ID_VAL, AD_ID_VAL, CDS_AD_ID_VAL, DOC_AD_ID_VAL, UD_ID_VAL, EVENTO_COMP, STU_FREQ_FLG_COMP, STU_NO_AUT_FLG_COMP);






CREATE UNIQUE INDEX XAKDOCENTI_MATRICOLA ON DOCENTI (MATRICOLA);
CREATE UNIQUE INDEX XAKP02_RISPOSTE ON P02_RISPOSTE (QUESITO_ID, QUEST_COMP_ID) ;
CREATE UNIQUE INDEX XAKP06_CDS_COD ON P06_CDS (COD) ;
CREATE UNIQUE INDEX XAKP07_NORMATIVA ON P07_NORMATIVA (NORM_COD) ;
CREATE UNIQUE INDEX XAKP09_AD_GEN ON P09_AD_GEN (COD);
CREATE UNIQUE INDEX XPKDOCENTI ON DOCENTI (DOCENTE_ID);
CREATE UNIQUE INDEX XPKELEMENTI ON ELEMENTI (ELEM_COD);
CREATE UNIQUE INDEX XPKP01_SCUOLA ON P01_SCUOLA (SCUOLA_SUP_ID) ;
CREATE UNIQUE INDEX XPKP02_QUESITI ON P02_QUESITI (QUESITO_ID) ;
CREATE UNIQUE INDEX XPKP02_QUEST_COMP ON P02_QUEST_COMP (QUEST_COMP_ID) ;
CREATE UNIQUE INDEX XPKP02_RISPOSTE ON P02_RISPOSTE (RISPOSTA_ID) ;
CREATE UNIQUE INDEX XPKP02_TIPI_FORMATO ON P02_TIPI_FORMATO (TIPO_FORMATO_COD) ;
CREATE UNIQUE INDEX XPKP06_CDS ON P06_CDS (CDS_ID) ;
CREATE UNIQUE INDEX XPKP06_FAC ON P06_FAC (FAC_ID);
CREATE UNIQUE INDEX XPKP06_FAC_CDS ON P06_FAC_CDS (CDS_ID, FAC_ID) ;
CREATE UNIQUE INDEX XPKP07_NORMATIVA ON P07_NORMATIVA (NORM_ID) ;
CREATE UNIQUE INDEX XPKP09_AD_GEN ON P09_AD_GEN (AD_ID);
CREATE UNIQUE INDEX XPKP09_UD_CDS ON P09_UD_CDS (AD_ID, CDS_ID, AA_OFF_ID, UD_ID) ;
CREATE UNIQUE INDEX XPKP09_UD_PDSORD_DOC ON P09_UD_PDSORD_DOC (CDS_ID, AA_OFF_ID, AD_ID, DOCENTE_ID, AA_ORD_ID, PDS_ID, UD_ID);
CREATE UNIQUE INDEX XPKTIPI_CORSO ON TIPI_CORSO (TIPO_CORSO_COD) ;
CREATE UNIQUE INDEX XPKTIPI_TITOLO_SUP ON TIPI_TITOLO_SUP (TIPO_TITOLO_COD);