select q35_dati_comp.aa_off_ad_id_val,count(*) 
FROM esse3.P02_QUESITI 
LEFT OUTER JOIN esse3.P02_TIPI_FORMATO ON (P02_QUESITI.TIPO_FORMATO_COD = P02_TIPI_FORMATO.TIPO_FORMATO_COD)
LEFT OUTER JOIN esse3.ELEMENTI ELEMENTO_P02_QUESITI ON (P02_QUESITI.ELEM_COD = ELEMENTO_P02_QUESITI.ELEM_COD)
LEFT OUTER JOIN esse3.P02_RISPOSTE ON (P02_QUESITI.QUESITO_ID = P02_RISPOSTE.QUESITO_ID)
LEFT OUTER JOIN esse3.P02_QUEST_COMP P02_QUEST_COMP_RISPOSTE ON (P02_RISPOSTE.QUEST_COMP_ID = P02_QUEST_COMP_RISPOSTE.QUEST_COMP_ID)
LEFT OUTER JOIN esse3.P02_QUESITI QUESITI_PADRE ON (P02_QUESITI.PARENT_QUESITO_ID = QUESITI_PADRE.QUESITO_ID) 
LEFT OUTER JOIN esse3.ELEMENTI ELEMENTO_QUESITI_PADRE ON (QUESITI_PADRE.ELEM_COD = ELEMENTO_QUESITI_PADRE.ELEM_COD)
JOIN esse3.V02_RISPOSTE_ROW_TESTO_LIBERO ON (P02_RISPOSTE.RISPOSTA_ID = V02_RISPOSTE_ROW_TESTO_LIBERO.RISPOSTA_ID)
LEFT OUTER JOIN esse3.Q35_DATI_COMP ON (P02_RISPOSTE.QUEST_COMP_ID = Q35_DATI_COMP.QUEST_COMP_ID)
LEFT OUTER JOIN esse3.P06_CDS Q35_CDS_AD_VAL ON (Q35_DATI_COMP.CDS_AD_ID_VAL = Q35_CDS_AD_VAL.CDS_ID)
JOIN esse3.P06_FAC_CDS Q35_FAC_CDS_AD_VAL ON ((Q35_CDS_AD_VAL.CDS_ID = Q35_FAC_CDS_AD_VAL.CDS_ID) AND Q35_FAC_CDS_AD_VAL.DEF_AMM_FLG=1)
LEFT OUTER JOIN esse3.P06_FAC Q35_FAC_AD_VAL ON (Q35_FAC_CDS_AD_VAL.FAC_ID = Q35_FAC_AD_VAL.FAC_ID)
LEFT OUTER JOIN esse3.DOCENTI Q35_DOCENTE_AD_VAL ON (Q35_DATI_COMP.DOC_AD_ID_VAL = Q35_DOCENTE_AD_VAL.DOCENTE_ID)
LEFT OUTER JOIN esse3.DOCENTI Q35_DOCENTE_TIT_AD_VAL ON (Q35_DATI_COMP.DOC_TIT_AD_ID_VAL = Q35_DOCENTE_TIT_AD_VAL.DOCENTE_ID)
LEFT OUTER JOIN esse3.P06_FAC Q35_FAC_COMP ON (Q35_DATI_COMP.FAC_ID_COMP = Q35_FAC_COMP.FAC_ID)
LEFT OUTER JOIN esse3.P06_CDS Q35_CDS_COMP ON (Q35_DATI_COMP.CDS_ID_COMP = Q35_CDS_COMP.CDS_ID)
LEFT OUTER JOIN esse3.P09_AD_GEN Q35_P09_AD_GEN ON (Q35_DATI_COMP.AD_ID_VAL = Q35_P09_AD_GEN.AD_ID)
LEFT OUTER JOIN esse3.P09_UD_CDS Q35_P09_UD_CDS 
    ON ((Q35_DATI_COMP.AA_OFF_AD_ID_VAL = Q35_P09_UD_CDS.AA_OFF_ID) 
    AND (Q35_DATI_COMP.AD_ID_VAL = Q35_P09_UD_CDS.AD_ID)
    AND (Q35_DATI_COMP.CDS_AD_ID_VAL = Q35_P09_UD_CDS.CDS_ID)
    AND (Q35_DATI_COMP.UD_ID_VAL = Q35_P09_UD_CDS.UD_ID))
LEFT OUTER JOIN esse3.TIPI_TITOLO_SUP Q35_TIPI_TITOLO_SUP ON (Q35_DATI_COMP.TIPO_TITOLO_COD_COMP = Q35_TIPI_TITOLO_SUP.TIPO_TITOLO_COD)
LEFT OUTER JOIN esse3.P01_SCUOLA Q35_SCUOLA ON (Q35_DATI_COMP.SCUOLA_SUP_ID_COMP = Q35_SCUOLA.SCUOLA_SUP_ID)
LEFT OUTER JOIN esse3.TIPI_CORSO Q35_TIPI_CORSO_AD_VAL ON (Q35_CDS_AD_VAL.TIPO_CORSO_COD = Q35_TIPI_CORSO_AD_VAL.TIPO_CORSO_COD)
LEFT OUTER JOIN esse3.P07_NORMATIVA Q35_NORMATIVA_CDS_AD_VAL ON (Q35_CDS_AD_VAL.NORM_ID = Q35_NORMATIVA_CDS_AD_VAL.NORM_ID)
LEFT OUTER JOIN esse3.Q35_INVIO_SEGNALAZIONE ON (Q35_DATI_COMP.QUEST_COMP_ID = Q35_INVIO_SEGNALAZIONE.QUEST_COMP_ID) 
LEFT OUTER JOIN esse3.V06_CARICHE_SDR_VALIDE Q35_CARICHE_CDS_AD_VAL ON ((Q35_FAC_CDS_AD_VAL.CDS_ID = Q35_CARICHE_CDS_AD_VAL.STRUTT_ID)
    AND Q35_CARICHE_CDS_AD_VAL.SDR_TIP='CDS' 
	AND Q35_CARICHE_CDS_AD_VAL.CARICA_ID=95)
LEFT OUTER JOIN esse3.V06_CARICHE_SDR_VALIDE Q35_CARICHE_FAC_AD_VAL ON ((Q35_FAC_CDS_AD_VAL.FAC_ID = Q35_CARICHE_FAC_AD_VAL.STRUTT_ID)
    AND Q35_CARICHE_FAC_AD_VAL.SDR_TIP='FAC' 
	AND Q35_CARICHE_FAC_AD_VAL.CARICA_ID=97)
LEFT OUTER JOIN esse3.DOCENTI Q35_PRESIDE_FAC_AD_VAL ON (Q35_CARICHE_FAC_AD_VAL.MATRICOLA_DOCENTE = Q35_PRESIDE_FAC_AD_VAL.MATRICOLA)
LEFT OUTER JOIN esse3.DOCENTI Q35_PRESIDENTE_CDS_AD_VAL ON (Q35_CARICHE_CDS_AD_VAL.MATRICOLA_DOCENTE = Q35_PRESIDENTE_CDS_AD_VAL.MATRICOLA)
LEFT OUTER JOIN esse3.Q35_NUM_QUEST_CDS_DOC_UD 
    ON ((Q35_DATI_COMP.AA_OFF_AD_ID_VAL = Q35_NUM_QUEST_CDS_DOC_UD.AA_OFF_AD_ID_VAL)
    AND (Q35_DATI_COMP.AD_ID_VAL = Q35_NUM_QUEST_CDS_DOC_UD.AD_ID_VAL)
    AND (Q35_DATI_COMP.CDS_AD_ID_VAL = Q35_NUM_QUEST_CDS_DOC_UD.CDS_AD_ID_VAL)
    AND (Q35_DATI_COMP.DOC_AD_ID_VAL = Q35_NUM_QUEST_CDS_DOC_UD.DOC_AD_ID_VAL)
    AND (Q35_DATI_COMP.UD_ID_VAL = Q35_NUM_QUEST_CDS_DOC_UD.UD_ID_VAL)
    AND  (COALESCE(Q35_DATI_COMP.EVENTO_COMP,'BOZZA')=Q35_NUM_QUEST_CDS_DOC_UD.EVENTO_COMP) 
	AND  (COALESCE(Q35_DATI_COMP.STU_FREQ_FLG_COMP,999)=Q35_NUM_QUEST_CDS_DOC_UD.STU_FREQ_FLG_COMP) 
	AND  (COALESCE(Q35_DATI_COMP.STU_NO_AUT_FLG_COMP,999)=Q35_NUM_QUEST_CDS_DOC_UD.STU_NO_AUT_FLG_COMP))
LEFT OUTER JOIN esse3.P06_DIP Q35_DOC_AD_VAL_DIP_AFFERENZA ON (Q35_DOC_AD_VAL_DIP_AFFERENZA.DIP_ID = Q35_DOCENTE_AD_VAL.DIP_ID)
LEFT OUTER JOIN esse3.P09_UD_PDSORD_DOC Q35_UD_TIPO_COPERTURA ON ((Q35_DATI_COMP.AA_OFF_AD_ID_VAL = Q35_UD_TIPO_COPERTURA.AA_OFF_ID)
    AND (Q35_DATI_COMP.AA_ORD_AD_ID_VAL = Q35_UD_TIPO_COPERTURA.AA_ORD_ID)
    AND (Q35_DATI_COMP.AD_ID_VAL = Q35_UD_TIPO_COPERTURA.AD_ID)
    AND (Q35_DATI_COMP.CDS_AD_ID_VAL = Q35_UD_TIPO_COPERTURA.CDS_ID)
    AND (Q35_DATI_COMP.DOC_AD_ID_VAL = Q35_UD_TIPO_COPERTURA.DOCENTE_ID)
    AND (Q35_DATI_COMP.PDS_AD_ID_VAL = Q35_UD_TIPO_COPERTURA.PDS_ID)
    AND (Q35_DATI_COMP.UD_ID_VAL = Q35_UD_TIPO_COPERTURA.UD_ID)) 
    where p02_quesiti.questionario_id = 35 
        and (q35_dati_comp.aa_off_ad_id_val not in ('2016') 
        and q35_dati_comp.dataora_comp > to_date('31/12/2016','dd/mm/yyyy') or 
        q35_dati_comp.dataora_comp < to_date('01/01/2016','dd/mm/yyyy'))
        group by q35_dati_comp.aa_off_ad_id_val
		HAVING COUNT(*)>200000
        order by q35_dati_comp.aa_off_ad_id_val;
		

