CREATE TABLE "P02_RISPOSTE"  (	
	"RISPOSTA_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"QUESITO_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"QUEST_COMP_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"TESTO_LIBERO" VARCHAR2(4000 CHAR), 
	"USR_INS_ID" VARCHAR2(20 CHAR), 
	"DATA_INS" DATE, 
	"USR_MOD_ID" VARCHAR2(20 CHAR), 
	"DATA_MOD" DATE, 
	 CONSTRAINT "XAKP02_RISPOSTE" UNIQUE ("QUESITO_ID", "QUEST_COMP_ID"),
 	 CONSTRAINT "XPKP02_RISPOSTE" PRIMARY KEY ("RISPOSTA_ID"));
 

   COMMENT ON COLUMN "P02_RISPOSTE"."RISPOSTA_ID" IS 'Chiave univoca';
   COMMENT ON COLUMN "P02_RISPOSTE"."QUESITO_ID" IS 'Id univoco del quesito';
   COMMENT ON COLUMN "P02_RISPOSTE"."QUEST_COMP_ID" IS 'Id univoco del questionario compilato';
   COMMENT ON COLUMN "P02_RISPOSTE"."TESTO_LIBERO" IS 'Eventuale risposta testuale del quesito';
   COMMENT ON COLUMN "P02_RISPOSTE"."USR_INS_ID" IS 'Utente che ha inserito il record';
   COMMENT ON COLUMN "P02_RISPOSTE"."DATA_INS" IS 'Data di inserimento';
   COMMENT ON COLUMN "P02_RISPOSTE"."USR_MOD_ID" IS 'Ultimo utente che ha modificato il record';
   COMMENT ON COLUMN "P02_RISPOSTE"."DATA_MOD" IS 'Data di modifica';
   COMMENT ON TABLE "P02_RISPOSTE"  IS 'Tabella delle risposte compilate';

  CREATE INDEX "XIF_P02RISPOSTE_P02QSTCMP_01" ON "P02_RISPOSTE" ("QUEST_COMP_ID");

