CREATE TABLE "P02_QUESITI" 
   (	"QUESITO_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"ORD_VIS" NUMBER(*,0) DEFAULT 1 NOT NULL ENABLE, 
	"ELEM_COD" VARCHAR2(10 CHAR) NOT NULL ENABLE, 
	"PARENT_QUESITO_ID" NUMBER(10,0), 
	"QUESTIONARIO_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"TIPO_FORMATO_COD" VARCHAR2(10 CHAR), 
	"PUNTEGGIO" NUMBER(5,2), 
	"OBBLIGATORIO_FLG" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"NOTE" VARCHAR2(1000 CHAR), 
	"GRP_ESC_ID" NUMBER(10,0), 
	"INS_ID" NUMBER(10,0), 
	"COND_ID" NUMBER(10,0), 
	"USR_INS_ID" VARCHAR2(20 CHAR), 
	"DATA_INS" DATE, 
	"USR_MOD_ID" VARCHAR2(20 CHAR), 
	"DATA_MOD" DATE, 
	"LIM_MIN" VARCHAR2(10 CHAR), 
	"LIM_MAX" VARCHAR2(10 CHAR), 
	"TAG_COD" VARCHAR2(20 CHAR), 
	"FORMULA_RISP_ID" NUMBER(10,0), 
	"VISIBLE_FLG" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE, 
	"CATEG_COD" VARCHAR2(10 CHAR), 
	"PROC_ATTIVA_QUEST_ID" NUMBER(10,0), 
	"TIPO_LAYOUT_COD" VARCHAR2(10 CHAR), 
	"NUM_MAX_SCE" NUMBER(3,0), 
	"ELEM_DES" VARCHAR2(1000 CHAR), 
	"NO_STAT_FLG" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"NUM_MAX_VALORI" NUMBER(10,0) DEFAULT NULL, 
	"OPERANDO_DOM_ID" NUMBER(10,0) DEFAULT NULL, 
	 CONSTRAINT "XPKP02_QUESITI" PRIMARY KEY ("QUESITO_ID"));
   

  CREATE INDEX "XIF_P02QSTP05FRMLCLCTSS_01" ON "P02_QUESITI" ("FORMULA_RISP_ID") ;
  CREATE INDEX "XIF_P02QUESITI_LMNT_01" ON "P02_QUESITI" ("ELEM_COD");
  CREATE INDEX "XIF_P02QUESITI_P02CTGR_01" ON "P02_QUESITI" ("CATEG_COD");
  CREATE INDEX "XIF_P02QUESITI_P02PRCTTQST_01" ON "P02_QUESITI" ("PROC_ATTIVA_QUEST_ID");
  CREATE INDEX "XIF_P02QUESITI_P02QST_01" ON "P02_QUESITI" ("PARENT_QUESITO_ID");
  CREATE INDEX "XIF_P02QUESITI_P02TGS_01" ON "P02_QUESITI" ("TAG_COD");
  CREATE INDEX "XIF_P02QUESITI_P02TPFRMT_01" ON "P02_QUESITI" ("TIPO_FORMATO_COD") ;
  CREATE INDEX "XIF_P02QUESITI_P02TPLYT_01" ON "P02_QUESITI" ("TIPO_LAYOUT_COD"); 
  CREATE INDEX "XIF_P02QUESITI_P05CNDVRMPRT_01" ON "P02_QUESITI" ("COND_ID");
  CREATE INDEX "XIF_P02QUESITI_P08NSGRP_01" ON "P02_QUESITI" ("INS_ID");
  CREATE INDEX "XIF_P02QUESITI_P08PTSCGRP_01" ON "P02_QUESITI" ("GRP_ESC_ID");
  CREATE INDEX "XIF_P02_QUESITI_OPDOM" ON "P02_QUESITI" ("OPERANDO_DOM_ID");


 