CREATE TABLE "P09_UD_PDSORD_DOC" 
   (	"CDS_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"AA_OFF_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"AD_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"AA_ORD_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"PDS_ID" NUMBER(10,0) DEFAULT NULL NOT NULL ENABLE, 
	"UD_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"DOCENTE_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"TIPO_COPERTURA_COD" VARCHAR2(5 CHAR), 
	"USR_INS_ID" VARCHAR2(20 CHAR), 
	"DATA_INS" DATE, 
	"USR_MOD_ID" VARCHAR2(20 CHAR), 
	"DATA_MOD" DATE, 
	"CUIN" VARCHAR2(20 BYTE), 
	"NO_TRASP_FLG" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	 CONSTRAINT "C_P09UDPDSORDDOC_014" CHECK (no_trasp_flg BETWEEN 0 AND 1) ENABLE, 
	 CONSTRAINT "XPKP09_UD_PDSORD_DOC" PRIMARY KEY ("CDS_ID", "AA_OFF_ID", "AD_ID", "DOCENTE_ID", "AA_ORD_ID", "PDS_ID", "UD_ID"));
  
   COMMENT ON COLUMN "P09_UD_PDSORD_DOC"."CDS_ID" IS 'ID del Corso di Studio';
   COMMENT ON COLUMN "P09_UD_PDSORD_DOC"."AA_OFF_ID" IS 'ID anno accademico offerta';
   COMMENT ON COLUMN "P09_UD_PDSORD_DOC"."AD_ID" IS 'ID dell´Attività Didattica';
   COMMENT ON COLUMN "P09_UD_PDSORD_DOC"."AA_ORD_ID" IS 'ID dell''''anno accademico dell''''ordinamento del CDS.';
   COMMENT ON COLUMN "P09_UD_PDSORD_DOC"."PDS_ID" IS 'ID del percorso di studio.';
   COMMENT ON COLUMN "P09_UD_PDSORD_DOC"."UD_ID" IS 'ID dell´Unità Didattica.';
   COMMENT ON COLUMN "P09_UD_PDSORD_DOC"."DOCENTE_ID" IS 'ID docente.';
   COMMENT ON COLUMN "P09_UD_PDSORD_DOC"."TIPO_COPERTURA_COD" IS 'Codice tipo di copertura del docente (es. supplente, ordinario prima fascia, seconda fascia, ecc).';
   COMMENT ON COLUMN "P09_UD_PDSORD_DOC"."USR_INS_ID" IS 'Utente di inserimento.';
   COMMENT ON COLUMN "P09_UD_PDSORD_DOC"."DATA_INS" IS 'Data di inserimento.';
   COMMENT ON COLUMN "P09_UD_PDSORD_DOC"."USR_MOD_ID" IS 'Utente di ultima modifica.';
   COMMENT ON COLUMN "P09_UD_PDSORD_DOC"."DATA_MOD" IS 'Data di ultima modifica.';
   COMMENT ON COLUMN "P09_UD_PDSORD_DOC"."NO_TRASP_FLG" IS 'Docente che non deve essere inviato alla trasparenza';
   COMMENT ON TABLE "P09_UD_PDSORD_DOC"  IS 'Docenti associati all´unità didattica dell´Offerta Didattica, con indicato il tipo di copertura.';

  CREATE INDEX "XIEP09UDPDSORDDOC_ADDOC" ON "P09_UD_PDSORD_DOC" ("AD_ID", "DOCENTE_ID");
  CREATE INDEX "XIF_P09DPDSRDDCP09DPDSRD_01" ON "P09_UD_PDSORD_DOC" ("CDS_ID", "AD_ID", "AA_ORD_ID", "PDS_ID", "AA_OFF_ID", "UD_ID");
  CREATE INDEX "XIF_P09UDPDSORDDOC_DCNT_01" ON "P09_UD_PDSORD_DOC" ("DOCENTE_ID");
  CREATE INDEX "XIF_P09UDPDSORDDOC_TPCPRTR_01" ON "P09_UD_PDSORD_DOC" ("TIPO_COPERTURA_COD");

