CREATE TABLE "Q35_NUM_QUEST_CDS_DOC_UD" 
   (	"AA_OFF_AD_ID_VAL" NUMBER, 
	"AD_ID_VAL" NUMBER, 
	"AD_VAL_COD" VARCHAR2(10 CHAR), 
	"AD_VAL_DENOMINAZIONE" VARCHAR2(255 CHAR), 
	"CDS_AD_ID_VAL" NUMBER, 
	"CDS_AD_VAL_COD" VARCHAR2(10 CHAR), 
	"CDS_AD_VAL_DENOMINAZIONE" VARCHAR2(255 CHAR), 
	"CDS_AD_VAL_TIPO_CORSO" VARCHAR2(10 CHAR), 
	"CDS_AD_VAL_TIPO_CORSO_DES" VARCHAR2(80 CHAR), 
	"CDS_AD_VAL_DURATA_ANNI" NUMBER(5,0), 
	"CDS_AD_VAL_NORMATIVA" VARCHAR2(10 CHAR), 
	"FAC_AD_VAL_COD" VARCHAR2(10 CHAR), 
	"FAC_AD_VAL_DENOMINAZIONE" VARCHAR2(255 CHAR), 
	"DOC_AD_ID_VAL" NUMBER, 
	"EVENTO_COMP" VARCHAR2(1074 CHAR), 
	"STU_FREQ_FLG_COMP" NUMBER, 
	"STU_NO_AUT_FLG_COMP" NUMBER, 
	"UD_ID_VAL" NUMBER, 
	"UD_VAL_COD" VARCHAR2(20 CHAR), 
	"UD_VAL_DENOMINAZIONE" VARCHAR2(255 CHAR), 
	"NUM_QUEST_COMP" NUMBER
   );

  CREATE INDEX "ESSE3"."IDX1_Q35_NUM_QUEST_CDS_DOC_UD" ON "ESSE3"."Q35_NUM_QUEST_CDS_DOC_UD" ("AA_OFF_AD_ID_VAL", "AD_ID_VAL", "CDS_AD_ID_VAL", "DOC_AD_ID_VAL", "UD_ID_VAL", "EVENTO_COMP", "STU_FREQ_FLG_COMP", "STU_NO_AUT_FLG_COMP”);
  