 CREATE TABLE "Q35_DATI_COMP" (
 "QUEST_COMP_ID" NUMBER(10,0), 
 "AA_CFU_STU_COMP" NUMBER, 
 "AA_ID_COMP" NUMBER, 
 "AA_IMM1_COMP" NUMBER, 
 "AA_IMM_SU_COMP" NUMBER, 
 "AA_ISCR_ID_COMP" NUMBER, 
 "AA_OFF_AD_ID_VAL" NUMBER, 
 "AA_ORD_AD_ID_VAL" NUMBER, 
 "AA_ORD_ID_COMP" NUMBER, 
 "AD_ID_VAL" NUMBER, 
 "ANNO_CORSO_AD_VAL" NUMBER, 
 "ANNO_CORSO_COMP" NUMBER, 
 "ANNO_MATUR_COMP" NUMBER, 
 "ANNO_NASCITA_COMP" NUMBER, 
 "CDS_AD_ID_VAL" NUMBER, 
 "CDS_ID_COMP" NUMBER, 
 "CFU_AA_STU_COMP" NUMBER, 
 "CFU_ACQ_STU_COMP" NUMBER, 
 "CITT_COD_COMP" VARCHAR2(1074 CHAR), 
 "DATAORA_COMP" DATE, 
 "DOC_AD_ID_VAL" NUMBER, 
 "DOC_TIT_AD_ID_VAL" NUMBER,
 "DOM_PART_AD_COD_VAL" VARCHAR2(1074 CHAR), 
 "EVENTO_COMP" VARCHAR2(1074 CHAR) , 
 "FAC_ID_COMP" NUMBER, 
 "FAT_PART_AD_COD_VAL" VARCHAR2(1074 CHAR), 
 "LODE_MATUR_FLG_COMP" NUMBER, 
 "MEDIA_STU_COMP" NUMBER, 
 "NAZ_MATUR_ID_COMP" NUMBER, 
 "NAZ_ORD_TIT_ID_COMP" NUMBER, 
 "NAZ_RES_ID_COMP" NUMBER, 
 "PART_AD_COD_VAL" VARCHAR2(1074 CHAR), 
 "PDS_AD_ID_VAL" NUMBER, 
 "PDS_ID_COMP" NUMBER, 
 "PROF_COD_COMP" VARCHAR2(1074 CHAR), 
 "PROV_NASC_COMP" VARCHAR2(1074 CHAR), 
 "PROV_RES_COMP" VARCHAR2(1074 CHAR), 
 "SCUOLA_SUP_ID_COMP" NUMBER,
 "SEDE_ID_COMP" NUMBER, 
 "SESSO_COMP" VARCHAR2(1074 CHAR), 
 "STU_FREQ_FLG_COMP" NUMBER, 
 "STU_NO_AUT_FLG_COMP" NUMBER, 
 "TIPO_CRE_AD_COD_VAL" VARCHAR2(1074 CHAR), 
 "TIPO_DID_COD_COMP" VARCHAR2(1074 CHAR), 
 "TIPO_ISCR_COD_COMP" VARCHAR2(1074 CHAR), 
 "TIPO_TITOLO_COD_COMP" VARCHAR2(1074 CHAR), 
 "TIPO_TITST_COD_COMP" VARCHAR2(1074 CHAR), 
 "UD_ID_VAL" NUMBER, 
 "VOTO_ALFA_MATUR_COMP" VARCHAR2(1074 CHAR), 
 "VOTO_MATUR_COMP" NUMBER, 
 "VOTO_MAX_MATUR_COMP" NUMBER, 
 "VOTO_MIN_MATUR_COMP" NUMBER);

CREATE INDEX "IDX1_Q35_DATI_COMP" ON "Q35_DATI_COMP" ("QUEST_COMP_ID");
CREATE INDEX "IDX2_Q35_DATI_COMP" ON "Q35_DATI_COMP" ("CDS_AD_ID_VAL");
CREATE INDEX "IDX3_Q35_DATI_COMP" ON "Q35_DATI_COMP" ("DOC_AD_ID_VAL");
CREATE INDEX "IDX4_Q35_DATI_COMP" ON "Q35_DATI_COMP" ("DOC_TIT_AD_ID_VAL");
CREATE INDEX "IDX5_Q35_DATI_COMP" ON "Q35_DATI_COMP" ("FAC_ID_COMP");
CREATE INDEX "IDX6_Q35_DATI_COMP" ON "Q35_DATI_COMP" ("CDS_ID_COMP");
CREATE INDEX "IDX7_Q35_DATI_COMP" ON "Q35_DATI_COMP" ("AD_ID_VAL");
CREATE INDEX "IDX8_Q35_DATI_COMP" ON "Q35_DATI_COMP" ("AA_OFF_AD_ID_VAL","AD_ID_VAL","CDS_AD_ID_VAL","UD_ID_VAL");
CREATE INDEX "IDX9_Q35_DATI_COMP" ON "Q35_DATI_COMP" ("TIPO_TITOLO_COD_COMP");
CREATE INDEX "IDX10_Q35_DATI_COMP" ON "Q35_DATI_COMP" ("SCUOLA_SUP_ID_COMP");
CREATE INDEX "IDX11_Q35_DATI_COMP" ON "Q35_DATI_COMP" ("AA_OFF_AD_ID_VAL","AD_ID_VAL","CDS_AD_ID_VAL","DOC_AD_ID_VAL","UD_ID_VAL","EVENTO_COMP","STU_FREQ_FLG_COMP","STU_NO_AUT_FLG_COMP");
CREATE INDEX "IDX12_Q35_DATI_COMP" ON "Q35_DATI_COMP" ("AA_OFF_AD_ID_VAL");
CREATE INDEX "IDX13_Q35_DATI_COMP" ON "Q35_DATI_COMP" ("DATAORA_COMP");
CREATE INDEX "IDX14_Q35_DATI_COMP" ON "Q35_DATI_COMP" ("AA_ORD_AD_ID_VAL","AD_ID_VAL","CDS_AD_ID_VAL","DOC_AD_ID_VAL","PDS_AD_ID_VAL","UD_ID_VAL");

 